### ISSUE TITLE
fps of extracted irCSN feature

### ISSUE THREAD

**Issue by AllenXuuu** [facebookresearch/AVT#11]
Hi. Thanks for your good work in AVT. But I have some questions about your extracted irCSN feature. What's the fps of your provided  ''ek100/ig65m_ftEk100_logits_10fps1s/rgb/'data.mdb'' and ''ek55/ig65m_ftEk55train_logits_25fps/rgb/data.mdb''. It looks strange for me...

**Comment by rohitgirdhar** [comment]
Hi, thanks for your interest. The EK55 features should be at 25fps, and for EK100 10FPS.
