### ISSUE TITLE
Regarding sampling method and strategy

### ISSUE THREAD

**Issue by ofir1080** [facebookresearch/AVT#19]
Hi again :)
I have had some wonders regarding the frame sampling method. Would be highly appreciated to clear that out... :)
Looking at expt. `09_ek55_avt` settings, the following parameters are:
- tau_o: 20sec
- original fps (of EK): 60
- req_fps: 1
- frames_per_clip: 10
- sampling_strategy: "last_clip"

As I see it,  in practice out of a 20-second input clip (1200 frames), only 10 are sampled, where each frame represents 1-second sub-clip. As a result (due to req_fps=1 and sampling_strategy='last_clip') the model only looks at the **last** 10 seconds. Is that correct? If so, what is the actual roll of tau_o?

Thank you very much!

**Comment by rohitgirdhar** [comment]
Ah sorry for missing this qs. 
So it should support >1 frame in a sub-clip, which is what I used to extract irCSN-152 features. Though for all configs released it doesn't need it. 
So the stride in this case defines how the subclips are sampled, not how the frames are sampled within the subclip: https://github.com/facebookresearch/AVT/blob/2d6781d5315a4c53bd059b1cd11ee46bd4427648/datasets/base_video_dataset.py#L699
By default it is set to the same as the number of frames in the subclip so it selects non overlapping subclips (https://github.com/facebookresearch/AVT/blob/2d6781d5315a4c53bd059b1cd11ee46bd4427648/conf/data/default.yaml#L13)

**Comment by ofir1080** [comment]
Thanks!
