### ISSUE TITLE
About EK55.

### ISSUE THREAD

**Issue by AllenXuuu** [facebookresearch/AVT#20]
Hi, thanks for your work. But I'm confused about details of fusing your result on EPIC-KITCHENS-55 test-set. Could you please give more explanation? Besides, it will be most kind of you to provide your submission file on EK55-test.

**Comment by rohitgirdhar** [comment]
Hi, we late fuse our predictions, with the predictions from [this paper](https://arxiv.org/abs/2006.00830). The submission file is [here](https://dl.fbaipublicfiles.com/avt/challenge_submissions/ek55.zip).
