### ISSUE TITLE
Number of GPUs Used During End-to-end Training

### ISSUE THREAD

**Issue by okay-okay** [facebookresearch/AVT#22]
Hi,

I was wondering how many GPUs you used for end-to-end training, for a single run? How long did those runs take? Thanks!

**Comment by okay-okay** [comment]
^^ Just wanted to bump on this, thanks!

**Comment by rohitgirdhar** [comment]
Hi sorry for the delay. It took around 18 hours on 32 V100 GPUs for the end-to-end architecture.
