### ISSUE TITLE
[Question] Video frame prediction without actions

### ISSUE THREAD

**Issue by austinmw** [facebookresearch/AVT#24]
If I have a set of videos with no labeled actions, can I use this to just predict the next frame in a video?

**Comment by rohitgirdhar** [comment]
Hi @austinmw 
Apologies for the delay in responding. The model performs future prediction in the feature space. The features are then projected into a distribution over actions using a linear layer. In principle, that linear projection can be replaced with a decoder network to generate pixel values, however we did not experiment with that in this paper.
