### ISSUE TITLE
Doubts regarding the Causality

### ISSUE THREAD

**Issue by Anirudh257** [facebookresearch/AVT#28]
@rohitgirdhar Thanks for this excellent work and releasing the code.

I went through the code but I am unable to see where the masking of inputs is occurring. In https://github.com/facebookresearch/AVT/blob/2d6781d5315a4c53bd059b1cd11ee46bd4427648/models/future_prediction.py#L178 you directly pass the entire input features to the GPT itself. Does the masking and output per timesteps get taken care by GPT itself?

**Comment by rohitgirdhar** [comment]
Hi @Anirudh257 thanks for your interest. Yes, the masking operations happen within the GPT implementation itself.

**Comment by Anirudh257** [comment]
Thanks for the clarification @rohitgirdhar. I was confused as to how the features were changing at different time-steps.
