### ISSUE TITLE
Use RULSTM feature

### ISSUE THREAD

**Issue by sanketsans** [facebookresearch/AVT#34]
Hi, I am trying to use rulstm as the backbone, but not sure which expts is required for it.

**Comment by Anirudh257** [comment]
I think only these experiments: 
https://github.com/facebookresearch/AVT/blob/main/expts/06_ek100_avt_tsnflow.txt and https://github.com/facebookresearch/AVT/blob/main/expts/06_ek100_avt_tsnflow.txt use rulstm features.

**Comment by rohitgirdhar** [comment]
I don't use RULSTM as the backbone, however I do have experiments with TSN as the backbone (which is what RULSTM uses as a backbone too). All the files in `expts/` that have a `_tsn` in the name are the ones that have that backbone. Those configs would have `+dataset_train.reader_fn={_target_: datasets.epic_kitchens.EpicRULSTMFeatsReader, ...` in it, which specifies where it will read the data from.
