### ISSUE TITLE
Data preparation (EK) 

### ISSUE THREAD

**Issue by ofir1080** [facebookresearch/AVT#36]
Hi There!
As mentioned, for faster processing all videos are resized to 256x256px.
However, when running evaluation on the provided ckpt (`expts/09_ek55_avt.txt`), I got different results on resized/original-size versions. The reported top-{1,5} acc was applied on the **original sized** vidoes?
My results are:
original videos' size:

`[2022-02-23 18:09:48,322][root][INFO] - acc1/action: 12.369477`
`[2022-02-23 18:09:48,323][root][INFO] - acc5/action: 29.859437`

on the resized videos:
`[2022-02-23 18:09:56,238][root][INFO] - acc1/action: 11.646586`
`[2022-02-23 18:09:56,238][root][INFO] - acc5/action: 26.666666`

I might have missed something?
Thank you very much for your work!

**Comment by rohitgirdhar** [comment]
Hi @ofir1080, that is strange.. I did all the training and evaluation on the low-resolution clips. Did you use [this](https://github.com/facebookresearch/AVT/blob/main/sample_scripts/resize_epic_256px.sh) for resize? Note that I don't resize to 256x256, but to height=256px.

**Comment by ofir1080** [comment]
Thanks for your response!
I will recheck it. I suspect it is a dataset version issue, as you suggested.
Thanks!
