### ISSUE TITLE
Can I train AVT on RGB frames?

### ISSUE THREAD

**Issue by forrestsz** [facebookresearch/AVT#37]
Hi, the official epic-kitchen provide both the rgb-frame and raw videso source, i want to ask, can i train your model in the rgb-frames, since the raw videos are too large to download for me.
if yes, would it lead to lower performance?

thanks!

**Comment by rohitgirdhar** [comment]
Hi @linqinghong thanks for your interest. I haven't experimented with the frames but in principle it should be possible to train with those too. I'm not sure what frame-rate the frames are extracted at, but given I anyway sample at 1FPS for many experiments, frames should give reasonably similar performance. You would have to change the data loaders etc though to make it work with frames

**Comment by forrestsz** [comment]
thanks!
