### ISSUE TITLE
Problem when reproducing with Breakfast/50Salad data

### ISSUE THREAD

**Issue by wasabipretzel** [facebookresearch/AVT#43]
Hi @rohitgirdhar , Thank you for great idea in video anticipation.

I'm reproducing your work with Breakfast/50salad data, and faced with 2 problem.

1.Do I have to locate breakfast video and 50 salad video at same folder?

2. While training with 50 Salad, ffmpeg returning some error  : marker does not match f_code
    (image below). Although with this error, training goes well but how can i handle this error? I've changed avi with mp4 file, or resizing it, but not worked. Is this because of codec problem?
![Untitled](https://user-images.githubusercontent.com/115709897/196073860-c7cd0a22-a316-4942-88fd-26e82e11796a.png)

Thank you

**Comment by CeeZh** [comment]
Hi, I'm also trying to reproduce on 50Salads. Do you know where I can find the annotations? It seems AVT stores the annotations in `external\` but i didn't find them.
Thank you!

**Comment by wasabipretzel** [comment]
@CeeZh 
Hi, in github AVT/external, you can see the link of annotation of epic kitchens. Git clone the annotation you want to reproduce(e.g https://github.com/epic-kitchens/epic-kitchens-100-annotations/tree/31ee70e9ebbf0f50fb455abbac34dc652c48df9a)
at inside of external folder, then you can use it.
