### ISSUE TITLE
Plans to release EK-55 / EGTEA Gaze+ models?

### ISSUE THREAD

**Issue by haofengac** [facebookresearch/AVT#5]
Hi, is there any plan to release EK-55 and EGTEA Gaze+ models to the Model Zoo? Any help is greatly appreciated!

**Comment by rohitgirdhar** [comment]
Hi Haofeng, thanks for your interest. The models should be all in [docs/MODELS.md](docs/MODELS.md).

**Comment by haofengac** [comment]
Hi @rohitgirdhar, I have trouble loading the models irCSN-152 (IG65M) for EK-55. When I'm using `expts/10_ek55_avt_ig65m.txt` I get the error below:

`RuntimeError: Error(s) in loading state_dict for BaseModel:
        Missing key(s) in state_dict: "future_predictor.gpt_model.h.8.ln_1.weight", "future_predictor.gpt_model.h.8.ln_1.bias", "future_predictor.gpt_model.h.8.attn.bias", "future_predictor.gpt_model.h.8.attn.masked_bias", "future_predictor.gpt_model.h.8.attn.c_attn.weight", "future_predictor.gpt_model.h.8.attn.c_attn.bias", "future_predictor.gpt_model.h.8.attn.c_proj.weight", "future_predictor.gpt_model.h.8.attn.c_proj.bias", "future_predictor.gpt_model.h.8.ln_2.weight", "future_predictor.gpt_model.h.8.ln_2.bias", "future_predictor.gpt_model.h.8.mlp.c_fc.weight", "future_predictor.gpt_model.h.8.mlp.c_fc.bias", "future_predictor.gpt_model.h.8.mlp.c_proj.weight", "future_predictor.gpt_model.h.8.mlp.c_proj.bias", "future_predictor.gpt_model.h.9.ln_1.weight", "future_predictor.gpt_model.h.9.ln_1.bias", "future_predictor.gpt_model.h.9.attn.bias", "future_predictor.gpt_model.h.9.attn.masked_bias", "future_predictor.gpt_model.h.9.attn.c_attn.weight", "future_predictor.gpt_model.h.9.attn.c_attn.bias", "future_predictor.gpt_model.h.9.attn.c_proj.weight", "future_predictor.gpt_model.h.9.attn.c_proj.bias", "future_predictor.gpt_model.h.9.ln_2.weight", "future_predictor.gpt_model.h.9.ln_2.bias", "future_predictor.gpt_model.h.9.mlp.c_fc.weight", "future_predictor.gpt_model.h.9.mlp.c_fc.bias", "future_predictor.gpt_model.h.9.mlp.c_proj.weight", "future_predictor.gpt_model.h.9.mlp.c_proj.bias", "future_predictor.gpt_model.h.10.ln_1.weight", "future_predictor.gpt_model.h.10.ln_1.bias", "future_predictor.gpt_model.h.10.attn.bias", "future_predictor.gpt_model.h.10.attn.masked_bias", "future_predictor.gpt_model.h.10.attn.c_attn.weight", "future_predictor.gpt_model.h.10.attn.c_attn.bias", "future_predictor.gpt_model.h.10.attn.c_proj.weight", "future_predictor.gpt_model.h.10.attn.c_proj.bias", "future_predictor.gpt_model.h.10.ln_2.weight", "future_predictor.gpt_model.h.10.ln_2.bias", "future_predictor.gpt_model.h.10.mlp.c_fc.weight", "future_predictor.gpt_model.h.10.mlp.c_fc.bias", "future_predictor.gpt_model.h.10.mlp.c_proj.weight", "future_predictor.gpt_model.h.10.mlp.c_proj.bias", "future_predictor.gpt_model.h.11.ln_1.weight", "future_predictor.gpt_model.h.11.ln_1.bias", "future_predictor.gpt_model.h.11.attn.bias", "future_predictor.gpt_model.h.11.attn.masked_bias", "future_predictor.gpt_model.h.11.attn.c_attn.weight", "future_predictor.gpt_model.h.11.attn.c_attn.bias", "future_predictor.gpt_model.h.11.attn.c_proj.weight", "future_predictor.gpt_model.h.11.attn.c_proj.bias", "future_predictor.gpt_model.h.11.ln_2.weight", "future_predictor.gpt_model.h.11.ln_2.bias", "future_predictor.gpt_model.h.11.mlp.c_fc.weight", "future_predictor.gpt_model.h.11.mlp.c_fc.bias", "future_predictor.gpt_model.h.11.mlp.c_proj.weight", "future_predictor.gpt_model.h.11.mlp.c_proj.bias".`

I'm guessing there is some shape mismatch between the model and the config. Do you know how can I fix this?
