### ISSUE TITLE
Data Augmentations Used on Training Data

### ISSUE THREAD

**Issue by okay-okay** [facebookresearch/AVT#6]
Hi, I'm wondering if you would be able to point out where in the repository you have defined data augmentations used on training data (if any)? For instance, in the kinetics dataloader: https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/kinetics.py they use TRAIN_JITTER_SCALES, TRAIN_CROP_SIZE, AUG.NUM_SAMPLE, etc. Thanks so much!

**Comment by rohitgirdhar** [comment]
Hi,
Yes, we define the augmentations in [`conf/data/defaults.yaml`](https://github.com/facebookresearch/AVT/blob/main/conf/data/default.yaml), which are sometimes overridden in the experiment configs. They are initialized in the train script [here](https://github.com/facebookresearch/AVT/blob/f1e6a9d7ad9cfd7992c3b05d2f75a3f59cdb2fdb/func/train.py#L550).
